- TwoSum.cpp
Problem:https://leetcode.com/problems/two-sum/
> TwoSum Solution

- CPP/ReverseInt.cpp
Problem = https://leetcode.com/problems/reverse-integer/
> Reverse Int solution

- Python/SingleNumber.py
Problem = https://leetcode.com/problems/single-number/
> Single Number Solution

- CPP/Add_Two_Numbers.cpp
Problem: https://leetcode.com/problems/add-two-numbers/
> CPP: Add Two Numbers solution

- Python/LongestSubstring.py
- Python/ZigZagConversion.py
problem = https://leetcode.com/problems/longest-substring-without-repeating-characters/submissions/
> Solution for Longest Substring Without Repeating Characters

- CPP/Palindrome.cpp
> CPP: Palindrome number Solution

- Python/RemoveDupFromSortedArray.py
- Python/RomanToInteger.py
problem = https://leetcode.com/problems/roman-to-integer
> Python : Add Roman To Integer Solution & Python: Add Remove Duplicates from Sorted Array Solution 

- Python/ReverseInteger.py
Problem = https://leetcode.com/problems/reverse-integer/
> Python: Add Reverse Integer Solution

- JAVA/Maximum_Product.java
Maximum Product of Two Elements in an Array
Problem Link : https://leetcode.com/problems/maximum-product-of-two-elements-in-an-array/
> JAVA : Maximum Product of Two Elements in an Array

- Java/Add_Two_Numbers.java
- Java/Longest_Substring_Without_Repeating_Characters.java
[Problem Link](https://leetcode.com/problems/add-two-numbers/submissions/)
> added Add_Two_Numbers in Java

- CPP/addString.cpp
- CPP/countAndSay.cpp
1. Add String
2. Count and Say
> Added String and Count problem

- Java/String_to_Integer_(atoi).java
[Problem Link](https://leetcode.com/problems/string-to-integer-atoi/)
> add atoi in Java

- CPP/Sudoku Solver.cpp
Problem Link: https://leetcode.com/problems/sudoku-solver/
> Sudoku Solver

- Golang/add-two-numbers.go
* Challenge Link: https://leetcode.com/problems/add-two-numbers/
> GO: add code for Adding two Numbers in GO

- Golang/two-sum.go
* Challenge Link: https://leetcode.com/problems/two-sum/
> GO: add code for two sum

- Java/Divide_Two_Integers.java
[Problem Link](https://leetcode.com/problems/divide-two-integers/submissions/
)
> add Divide_Two_Integers in Java

- CPP/Implement_strstr
Problem:- https://leetcode.com/problems/implement-strstr/
> CPP: Implement StrStr problem solution

- Golang/reverse_integer.go
Problem : https://leetcode.com/problems/reverse-integer/
> Golang: add solution for reverse integer.

- Golang/palindrome_number.go
Problem: https://leetcode.com/problems/palindrome-number
> Golang: solution for Palindrome problem

- Golang/valid_parenthesis.go
Problem: https://leetcode.com/problems/valid-parentheses
> Golang: Solution for Valid Parenthesis problem

- Golang/longest_substring_without_repeating_characters.go
Problem: https://leetcode.com/problems/longest-substring-without-repeating-characters
> Golang: Solution for Longest Substring without Repeating Characters

- Java/Longest_Common_Prefix.java
[Problem Link](https://leetcode.com/problems/longest-common-prefix/submissions/)
> Add Longest_Common_Prefix in Java

- Python/remove_duplicate.py
> remove duplicate from array

- Python/firstMissingPositive.py
Problem Link: https://leetcode.com/problems/first-missing-positive/
> Added first missing positive

- Python/3SumClosest.py
Problem Link: https://leetcode.com/problems/3sum-closest
> Added 3SumClosest

- Java/mergingTwoTrees.java
Challenge link: https://leetcode.com/problems/merge-two-binary-trees/
img:
> Merging two Binary Trees in Java

- Python/remove_element.py
https://leetcode.com/problems/remove-element/description/
> remove element (problem 27) python program added

- Golang/min_ticket.go
* Challenge Link: https://leetcode.com/problems/minimum-cost-for-tickets/
> go: add solution for Minimum Cost For Tickets problem

- reverse_integer.java
* Challenge Link: https://leetcode.com/problems/reverse-integer/
> java: add solutions to reverse integer in java

- Java/BestTimeToBuyAndSellStock.java
*Challenge Link: https://leetcode.com/problems/best-time-to-buy-and-sell-stock/
> java: add solution to stocks challenge

- Java/median_sorted.java
* Challenge Link: https://leetcode.com/problems/median-of-two-sorted-arrays
> java: add solution to find median sorted array

- Python/TwoSum.py
* Challenge Link: https://leetcode.com/problems/two-sum/
Signed-off-by: Abhinal <abhinavagarwalsps@gmail.com>
> Python: add solution to TwoSum Problem

- Python/AddTwoNumbers.py
- Python/MedianTwoSortedArrays.py
*Challenge Link: https://leetcode.com/problems/add-two-numbers/
Signed-off-by: Abhinal <abhinavagarwalsps@gmail.com>
> python: add solution to add two numbers

- Python/RegularExpressionMatching.py
*Challenge link: https://leetcode.com/problems/regular-expression-matching/
Signed-off-by: Abhinal <abhinavagarwalsps@gmail.com>
> Python: Add solution for Regular Expression Matching

- Python/MergeTwoListed.py
*Challenge link: https://leetcode.com/problems/merge-two-sorted-lists/
Signed-off-by: Abhinal <abhinavagarwalsps@gmail.com>
> Python: Add solution to merge two sorted list

- Mysql/Combine Two Tables
Link:https://leetcode.com/problems/combine-two-tables/
> Create  Combine Two Tables

- CPP/multiplystrings.cpp
Given two non-negative integers num1 and num2 represented as strings, return the product of num1 and num2, also represented as a string.
> Program for multiplying 2 strings

- Mysql/Second Highest Salary
Link: https://leetcode.com/problems/second-highest-salary/
> Create Second Highest Salary

- Mysql/Employees Earning More Than Their Managers
Link: https://leetcode.com/problems/employees-earning-more-than-their-managers/
> Create Employees Earning More Than Their Managers

- Mysql/duplicate emails
Link: https://leetcode.com/problems/duplicate-emails/
> MySQL query to delete duplicate email

- CPP/sqrt_number.cpp
Link:https://leetcode.com/problems/sqrtx/
> program to find square root of number

- CPP/UglyNumber.cpp
263. Ugly Number
Write a program to check whether a given number is an ugly number.
Ugly numbers are positive numbers whose prime factors only include 2, 3, 5.
Challenge Link :- https://leetcode.com/problems/ugly-number/
> Solution for UglyNumber.cpp

- CPP/addDigit.cpp
258. Add Digits
Given a non-negative integer num, repeatedly add all its digits until the result has only one digit.
Challenge Link : https://leetcode.com/problems/add-digits/
> Solution to Add Digits

- CPP/power of 2.cpp
231. Power of Two
Given an integer n, write a function to determine if it is a power of two.
Challenge Link : https://leetcode.com/problems/power-of-two/
> solution for power of two.cpp

- CPP/house robber.cpp
198. House Robber
You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security system connected and it will automatically contact the police if two adjacent houses were broken into on the same night.
Given a list of non-negative integers representing the amount of money of each house, determine the maximum amount of money you can rob tonight without alerting the police.
Challenge Link : https://leetcode.com/problems/house-robber/
> solution for house robber.cpp

- Mysql/department-highest-salary
Challenge Link :- https://leetcode.com/problems/department-highest-salary/
> solution for department-highest-salary

- Mysql/rank-scores
challenge link :- https://leetcode.com/problems/rank-scores/
> solution for rank-scores

- Mysql/consecutive-numbers
Challenge Link :- https://leetcode.com/problems/consecutive-numbers/
> solution for consecutive-numbers

- Mysql/swap-salary
Challenge Link :- https://leetcode.com/problems/swap-salary/
> solution for swap-salary

- Mysql/rising-temperature
https://leetcode.com/problems/rising-temperature/
> Solution for rising-temperature

- Mysql/nth-highest-salary
Challenge Link :- https://leetcode.com/problems/nth-highest-salary
> Solution for nth-highest-salary

- Mysql/duplicate-emails
Challenge Link :- https://leetcode.com/problems/duplicate-emails/
> Solution for duplicate-emails

- Mysql/classes-more-than-5-students
Challenge Link :- https://leetcode.com/problems/classes-more-than-5-students
> Solution for classes-more-than-5-students

- Mysql/department-top-three-salaries
Challenge Link :- https://leetcode.com/problems/department-top-three-salaries
> Solution for department-top-three-salaries

- Mysql/human-traffic-of-stadium
Challenge Link :- https://leetcode.com/problems/human-traffic-of-stadium/
> Solution for human-traffic-of-stadium

- Mysql/trips-and-users
Challenge Link :- https://leetcode.com/problems/trips-and-users
> Solution for trips-and-users

- CPP/zigzag.cpp
Challenge Link: https://leetcode.com/problems/zigzag-conversion/
> Program : Zigzag Conversion

- CPP/construct-the-rectangle.cpp
Challenge Link :- https://leetcode.com/problems/construct-the-rectangle
Submission Screenshot:
> C++ : creating rectangle (min. perimeter) for a given area

- JavaScript/palindrome-number.js
Challenge link :- https://leetcode.com/problems/palindrome-number/
> JavaScript: solution for palindrome-number

- JavaScript/two-sum.js
*LeetCode Problem 1
Challenge Link :- https://leetcode.com/problems/two-sum
> JavaScript: solution for two-sum

- Python/move_zeroes.py
input : [0,1,0,3,12]
output: [1,3,12,0,0]
> Move Zeroes

- Python/search_insert_position.py
Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.
Input: 
[1,3,5,6]
5
Output: 2
> Search Insert Position

- CPP/Min_Cost_Climbing_Stairs.cpp
LeetCode Problem 746
Challenge Link :- https://leetcode.com/problems/min-cost-climbing-stairs/
> Add Min Cost Climbing Stairs CPP solution

- Python/GenParentheses.py
*LeetCode Problem 22
Challenge link : https://leetcode.com/problems/generate-parentheses/
> Python: Generate Parentheses

- JavaScript/reverse-integer.js
Challenge link :- https://leetcode.com/problems/reverse-integer/
> JavaScript: solution for reverse integer

- Rust/zigzag-conversion.rs
> Rust: Added ZigZag Conversion Solution

- JavaScript/valid-parentheses.js
Challenge link :- https://leetcode.com/problems/valid-parentheses/
> JavaScript: Solution for 20. Valid Parentheses

- CPP/Longest_Substr_Without_RepeatingCharacters.cpp
LeetCode Problem 3
Challenge link :- https://leetcode.com/problems/longest-substring-without-repeating-characters/
> Add Longest Substring without repeating characters CPP solution

- CPP/ValidateBinarySearchTree.cpp
Challenge Link: [https://leetcode.com/problems/validate-binary-search-tree/](https://leetcode.com/problems/validate-binary-search-tree/)
> Add Validate Binary Search tree

- Rust/int_to_roman.rs
Problem Link:- https://leetcode.com/problems/integer-to-roman
> Rust: Added Int to roman

- Python/IntegerReplacement.py
- Python/String2Integer.py
*LeetCode Problem 397
Challenge link : https://leetcode.com/problems/integer-replacement/
> Python: Integer Replacement

- Python/strStr_Impl.py
*LeetCode problem 28
Challenge Link: https://leetcode.com/problems/implement-strstr/
> Python: Implement strStr()

- CPP/Longest_Common_Prefix.cpp
Added the cpp solution for Longest Common Prefix problem in LeetCode. Problem number 14.
https://leetcode.com/problems/longest-common-prefix/
> CPP Solution for Longest Common Prefix

- Python/multiply_strings.py
* https://leetcode.com/problems/multiply-strings/
> Python: multiply strings

- Python/count-and-say.py
*LeetCode problem 38
Challenge link: https://leetcode.com/problems/count-and-say/
> Python: Count and Say

- Trapping_Rain_Water.py
Link: https://leetcode.com/problems/trapping-rain-water/
> Python: Trapping rain water problem

- Golang/DistinctSubsequences.go
* https://leetcode.com/problems/distinct-subsequences/
> golang: Distinct Subsequences

- Python/Rotate_Image.py
Link: https://leetcode.com/problems/rotate-image/
> Python: Rotate Image

- Python/Group_Anagrams.py
Link: https://leetcode.com/problems/group-anagrams/
> Python: Grouping Anagrams

- Golang/FirstMissingPositive.go
* https://leetcode.com/problems/first-missing-positive/
> go: First Missing Positive

- CPP/remove_nth_node_from_end_of_list.cpp
link: https://leetcode.com/problems/remove-nth-node-from-end-of-list/
> CPP solution of remove nth node from end of list

- CPP/Spiral_Matrix.cpp
link: https://leetcode.com/problems/spiral-matrix/
> Cpp solution of Spiral Matrix

- CPP/Minimum_Path_sum.cpp
link: https://leetcode.com/problems/minimum-path-sum/
> CPP solution of minimum path sum

- CPP/Maximum_Subarray.cpp
LeetCode Problem 53
Challenge Link :- https://leetcode.com/problems/maximum-subarray/
> Add Maximum Subarray CPP solution

- CPP/flatten-nested-list-iterator.cpp
link: https://leetcode.com/problems/flatten-nested-list-iterator/
> CPP solution of flatten nested list iterator

- CPP/ComplexNumberMultiplication.cpp
Added the solution of Complex Number Multiplication in Cpp
Leetcode:537
Challenge Link : https://leetcode.com/problems/complex-number-multiplication/submissions/
> Add:Cpp Complex Number Multiplication

- CPP/Backspace_string_compare.cpp
Problem Link: https://leetcode.com/problems/backspace-string-compare/
> Add:Added the solution of Backspace string compare problem in cpp

- CPP/Find First and Last Position of Element in Sorted Array.cpp
Leetcode 34.
Problem Link: https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/
> Added the solution of Find First and Last Position of Element in Sorted Array in cpp

- Python/loud-and-rich.py
python code for the solution for problem number 851: loud and rich
> added solution for problem no. 851

- CPP/Number_of_islands.cpp
Challenge link: https://leetcode.com/problems/number-of-islands/
> [CPP] Added solution for number of islands

- CPP/PathSum.cpp
Challenge Link:- [https://leetcode.com/problems/path-sum/](https://leetcode.com/problems/path-sum/)
> Add path Sum

- CPP/Cherry-Pickup-II.cpp
challenge link :- https://leetcode.com/problems/cherry-pickup-ii/
> Solution for Cherry Pickup II

- CPP/Baseball-Game.cpp
challenge link :- https://leetcode.com/problems/baseball-game/
> Solution for Baseball-Game

- CPP/Integer-Break.cpp
Challenge link:- https://leetcode.com/problems/integer-break/
> Solution for Integer-break

- CPP/Count-Primes.cpp
challenge link :- https://leetcode.com/problems/count-primes/
> solution for count-primes

- JavaScript/divTwoInt.js
* https://leetcode.com/problems/divide-two-integers
> js: divide two integers problem

- Java/JumpGame.java
* https://leetcode.com/problems/jump-game/
> java: jump game solution

- Java/MinPathSum.java
* https://leetcode.com/problems/minimum-path-sum/
> java: minimum path sum

- Java/Pascals.java
* https://leetcode.com/problems/pascals-triangle
> java: pascals triangle

- Python/DecodeWays.py
https://leetcode.com/problems/decode-ways/
> Python: Add Solution for Decode ways

- Python/ZigzagConversion.py
https://leetcode.com/problems/zigzag-conversion/
> Python: Add Solution for Zigzag Conversion

- JavaScript/3Sum.js
https://leetcode.com/problems/3sum/
> Javascript: Add solution for 3Sum

- JavaScript/ValidSudoku.js
https://leetcode.com/problems/valid-sudoku/
> Javascript: Add Solution for Valid Sudoku

- CPP/PopulatingNextRightPointersInEachNode_II.cpp
- Java/PopulatingNextRightPointersInEachNode.java
problem: https://leetcode.com/problems/populating-next-right-pointers-in-each-node/
> Java: Populating Next Right Pointers in Each Node, cpp: Populating Next Right Pointers in Each Node II

- CPP/Find Minimum in Rotated Sorted Array II.cpp
challenge link: https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/
> CPP: Find Minimum in Rotated Sorted Array II

- Java/FindLargestValueInEachTreeRow.java
problem: https://leetcode.com/problems/find-largest-value-in-each-tree-row/
> Java: Find Largest Value in Each Tree Row

- CPP/NextGreaterElement_I.cpp
problem: https://leetcode.com/problems/next-greater-element-i/
> CPP: Next Greater Element I

- CPP/InvertBinaryTree.cpp
problem: https://leetcode.com/problems/invert-binary-tree/
> CPP: Invert Binary Tree

- CPP/sqrt_number_2.cpp
Leetcode problem: https://leetcode.com/problems/sqrtx/
> Added sqrt_number_2.cpp

- CPP/Sort Colors.cpp
challenge link: https://leetcode.com/problems/sort-colors/
> CPP: Sort colors solution

- CPP/Intersection_Of_Two_Arrays_II.cpp
Problem link : https://leetcode.com/problems/intersection-of-two-arrays-ii/
> Added Solution for Intersection of Two Arrays II

- CPP/Number_Of_Dice_Rolls_With_Target_Sum.cpp
Problem Link : https://leetcode.com/problems/number-of-dice-rolls-with-target-sum/
> Added Number of Dice Rolls With Target Sum Solution

- Python/Binary_Search_Tree_Traversals.py
I have added Binary search tree traversals:
-inorder
-preorder
-postorder
> Added Binary Search Tree Traversals

- CPP/Permutation_Sequence.cpp
Added Permutation Sequence Leetcode Problem Solution - https://leetcode.com/problems/permutation-sequence/
> Added Permutation Sequence problem Leetcode

- CPP/Missing Number.cpp
challenge link: https://leetcode.com/problems/missing-number/
> CPP: Missing Number

- JavaScript/MergeTwoSortedLists.js
- JavaScript/RemoveElement.js
- JavaScript/ValidParentheses.js
Problem - https://leetcode.com/problems/valid-parentheses/
> js: Add solution for Valid Parentheses

- Java/findallduplicatesinanarray.java
> Java program to find all duplicate elements in an array - Leetcode 442.

- CPP/palindrome_check.cpp
Hacktoberfest Contribution
Link: https://leetcode.com/problems/valid-palindrome/
> Palindrome Validation

- CPP/2d_matrix_search.cpp
Hacktoberfest Contribution
Link: https://leetcode.com/problems/search-a-2d-matrix/
> 2D Matrix Search using C++

- CPP/insertion_sort.cpp
Hacktoberfest Contribution
Link: https://leetcode.com/problems/insertion-sort-list/
> Insertion Sort Of Array

- CPP/BinarySearch.cpp
Problem link: https://leetcode.com/problems/binary-search/
> BinarySearch.cpp

- CPP/Single Number.cpp
Problem link: https://leetcode.com/problems/single-number/
> CPP: Single Number

- CPP/DailyTemperatures.cpp
Problem link: https://leetcode.com/problems/daily-temperatures/
> DailyTemperatures.cpp

- CPP/Detect-Capital.cpp
Problem link: https://leetcode.com/problems/detect-capital/
> Detect-Capital.cpp

- Python/palindrome-number.py
https://leetcode.com/problems/palindrome-number/
> Add solution for palindrome-number

- Python/baseball-game.py
https://leetcode.com/problems/baseball-game/
> Add solution for baseball-game

- Java/remove-element.java
https://leetcode.com/problems/remove-element/
>  Add solution for Remove Element

- Kotlin/two-sum.kt
https://leetcode.com/problems/two-sum/
> Add solution for Two Sum

- Kotlin/reverse-integer.kt
https://leetcode.com/problems/reverse-integer/
>  Add solution for Reverse Integer

- Python/valid-parentheses.py
https://leetcode.com/problems/valid-parentheses/
>  Add solution for Valid Parentheses

- Python/EarliestPossibleDayOfBloom.py
- Python/GroupAnagrams.py
Solution in Python3 for 2136. Earliest Possible Day of Bloom.
https://leetcode.com/problems/earliest-possible-day-of-full-bloom/
The same can be found on https://leetcode.com/ayamdobhal
> add solution for Earliest Possible Day of Bloom

- Python/GroupAnagrams.py
- Python/ImageOverlap.py
solution in python3 for 835. Image Overlap.
https://leetcode.com/problems/image-overlap/
> add solution for image overlap

- Python/ContinuousSubarraySum.py
solution in python3 for 523. continuous subarray sum.
https://leetcode.com/problems/continuous-subarray-sum/
> add solution for continuous subarray sum

- JavaScript/counter.js
Challenge Link: https://leetcode.com/problems/reverse-integer/
> JS: added solution for problem Counter

- JavaScript/sleep.js
Challenge Link: https://leetcode.com/problems/sleep/description/
> JS: Added solution for leetcode question Sleep in js

- JavaScript/array-prototype-last.js
Challenge Link: https://leetcode.com/problems/array-prototype-last/description/
> JS: Added solution for problem Array Prototype Last

- JavaScript/FunctionComposite.js
Challenge Link: https://leetcode.com/problems/function-composition/description/
> JS: Added solution for leetcode problem Function Composite

- Java/IsomorphicStrings.java
https://leetcode.com/problems/isomorphic-strings/description/
> Java: Add solution for Isomorphic Strings

- Cpp/detect_captial.cpp
https://leetcode.com/problems/single-number-iii/
> Cpp: detect_captial

- letter-combinations-of-a-phone-number.cpp
https://leetcode.com/problems/letter-combinations-of-a-phone-number/
> Cpp: letter-combinations-of-a-phone-number

- xor-operation-in-an-array.cpp
https://leetcode.com/problems/xor-operation-in-an-array/
> Cpp: Create xor-operation-in-an-array.cpp

- CPP/Path-Sum-II.cpp
https://leetcode.com/problems/path-sum-ii/
> Cpp: Path-Sum-II.cpp

- Cpp/number_of_island.cpp
https://leetcode.com/problems/number-of-islands/
> Cpp: number_of_island.cpp

- Python/zigzag-conversion.py
Problem link: https://leetcode.com/problems/zigzag-conversion
> python: add solution for zigzag-conversion (LeetCode #6)

- Python/string_to_integer_atoi.py
Problem link: https://leetcode.com/problems/string-to-integer-atoi/
> python: add solution for string-to-integer-atoi (LeetCode #8)
